// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/server/urlstore (interfaces: URLStoreSyncService)

// Package mock_urlstore is a generated GoMock package.
package mock_urlstore

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	urlstore "github.com/hotstone-seo/hotstone-seo/server/urlstore"
	reflect "reflect"
)

// MockURLStoreSyncService is a mock of URLStoreSyncService interface
type MockURLStoreSyncService struct {
	ctrl     *gomock.Controller
	recorder *MockURLStoreSyncServiceMockRecorder
}

// MockURLStoreSyncServiceMockRecorder is the mock recorder for MockURLStoreSyncService
type MockURLStoreSyncServiceMockRecorder struct {
	mock *MockURLStoreSyncService
}

// NewMockURLStoreSyncService creates a new mock instance
func NewMockURLStoreSyncService(ctrl *gomock.Controller) *MockURLStoreSyncService {
	mock := &MockURLStoreSyncService{ctrl: ctrl}
	mock.recorder = &MockURLStoreSyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockURLStoreSyncService) EXPECT() *MockURLStoreSyncServiceMockRecorder {
	return m.recorder
}

// Find mocks base method
func (m *MockURLStoreSyncService) Find(arg0 context.Context) ([]*urlstore.URLStoreSync, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].([]*urlstore.URLStoreSync)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockURLStoreSyncServiceMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockURLStoreSyncService)(nil).Find), arg0)
}

// FindOne mocks base method
func (m *MockURLStoreSyncService) FindOne(arg0 context.Context, arg1 int64) (*urlstore.URLStoreSync, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*urlstore.URLStoreSync)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne
func (mr *MockURLStoreSyncServiceMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockURLStoreSyncService)(nil).FindOne), arg0, arg1)
}

// GetLatestVersion mocks base method
func (m *MockURLStoreSyncService) GetLatestVersion(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersion", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersion indicates an expected call of GetLatestVersion
func (mr *MockURLStoreSyncServiceMockRecorder) GetLatestVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersion", reflect.TypeOf((*MockURLStoreSyncService)(nil).GetLatestVersion), arg0)
}

// GetListDiff mocks base method
func (m *MockURLStoreSyncService) GetListDiff(arg0 context.Context, arg1 int64) ([]*urlstore.URLStoreSync, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListDiff", arg0, arg1)
	ret0, _ := ret[0].([]*urlstore.URLStoreSync)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListDiff indicates an expected call of GetListDiff
func (mr *MockURLStoreSyncServiceMockRecorder) GetListDiff(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListDiff", reflect.TypeOf((*MockURLStoreSyncService)(nil).GetListDiff), arg0, arg1)
}

// Insert mocks base method
func (m *MockURLStoreSyncService) Insert(arg0 context.Context, arg1 urlstore.URLStoreSync) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockURLStoreSyncServiceMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockURLStoreSyncService)(nil).Insert), arg0, arg1)
}
