// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/server/service (interfaces: SettingService)

// Package service_mock is a generated GoMock package.
package service_mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	repository "github.com/hotstone-seo/hotstone-seo/server/repository"
	reflect "reflect"
)

// MockSettingService is a mock of SettingService interface
type MockSettingService struct {
	ctrl     *gomock.Controller
	recorder *MockSettingServiceMockRecorder
}

// MockSettingServiceMockRecorder is the mock recorder for MockSettingService
type MockSettingServiceMockRecorder struct {
	mock *MockSettingService
}

// NewMockSettingService creates a new mock instance
func NewMockSettingService(ctrl *gomock.Controller) *MockSettingService {
	mock := &MockSettingService{ctrl: ctrl}
	mock.recorder = &MockSettingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSettingService) EXPECT() *MockSettingServiceMockRecorder {
	return m.recorder
}

// Find mocks base method
func (m *MockSettingService) Find(arg0 context.Context) ([]*repository.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].([]*repository.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockSettingServiceMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSettingService)(nil).Find), arg0)
}

// FindOne mocks base method
func (m *MockSettingService) FindOne(arg0 context.Context, arg1 string) (*repository.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*repository.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne
func (mr *MockSettingServiceMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockSettingService)(nil).FindOne), arg0, arg1)
}

// Update mocks base method
func (m *MockSettingService) Update(arg0 context.Context, arg1 string, arg2 *repository.Setting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockSettingServiceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettingService)(nil).Update), arg0, arg1, arg2)
}
