// Code generated by MockGen. DO NOT EDIT.
// Source: app/repository/locale.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	repository "github.com/hotstone-seo/hotstone-seo/app/repository"
	reflect "reflect"
)

// MockLocaleRepo is a mock of LocaleRepo interface
type MockLocaleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLocaleRepoMockRecorder
}

// MockLocaleRepoMockRecorder is the mock recorder for MockLocaleRepo
type MockLocaleRepoMockRecorder struct {
	mock *MockLocaleRepo
}

// NewMockLocaleRepo creates a new mock instance
func NewMockLocaleRepo(ctrl *gomock.Controller) *MockLocaleRepo {
	mock := &MockLocaleRepo{ctrl: ctrl}
	mock.recorder = &MockLocaleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLocaleRepo) EXPECT() *MockLocaleRepoMockRecorder {
	return m.recorder
}

// FindOne mocks base method
func (m *MockLocaleRepo) FindOne(arg0 context.Context, arg1 int64) (*repository.Locale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*repository.Locale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne
func (mr *MockLocaleRepoMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockLocaleRepo)(nil).FindOne), arg0, arg1)
}

// Find mocks base method
func (m *MockLocaleRepo) Find(arg0 context.Context) ([]*repository.Locale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].([]*repository.Locale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockLocaleRepoMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLocaleRepo)(nil).Find), arg0)
}

// Insert mocks base method
func (m *MockLocaleRepo) Insert(arg0 context.Context, arg1 repository.Locale) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockLocaleRepoMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLocaleRepo)(nil).Insert), arg0, arg1)
}

// Delete mocks base method
func (m *MockLocaleRepo) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockLocaleRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLocaleRepo)(nil).Delete), arg0, arg1)
}

// Update mocks base method
func (m *MockLocaleRepo) Update(arg0 context.Context, arg1 repository.Locale) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockLocaleRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLocaleRepo)(nil).Update), arg0, arg1)
}
