// Code generated by MockGen. DO NOT EDIT.
// Source: app/service/provider_service.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	repository "github.com/hotstone-seo/hotstone-server/app/repository"
	service "github.com/hotstone-seo/hotstone-server/app/service"
	reflect "reflect"
)

// MockProviderService is a mock of ProviderService interface
type MockProviderService struct {
	ctrl     *gomock.Controller
	recorder *MockProviderServiceMockRecorder
}

// MockProviderServiceMockRecorder is the mock recorder for MockProviderService
type MockProviderServiceMockRecorder struct {
	mock *MockProviderService
}

// NewMockProviderService creates a new mock instance
func NewMockProviderService(ctrl *gomock.Controller) *MockProviderService {
	mock := &MockProviderService{ctrl: ctrl}
	mock.recorder = &MockProviderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProviderService) EXPECT() *MockProviderServiceMockRecorder {
	return m.recorder
}

// MatchRule mocks base method
func (m *MockProviderService) MatchRule(arg0 service.MatchRuleRequest) (*repository.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchRule", arg0)
	ret0, _ := ret[0].(*repository.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchRule indicates an expected call of MatchRule
func (mr *MockProviderServiceMockRecorder) MatchRule(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchRule", reflect.TypeOf((*MockProviderService)(nil).MatchRule), arg0)
}
