// Code generated by MockGen. DO NOT EDIT.
// Source: app/repository/urlstore_tree.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockURLStoreTree is a mock of URLStoreTree interface
type MockURLStoreTree struct {
	ctrl     *gomock.Controller
	recorder *MockURLStoreTreeMockRecorder
}

// MockURLStoreTreeMockRecorder is the mock recorder for MockURLStoreTree
type MockURLStoreTreeMockRecorder struct {
	mock *MockURLStoreTree
}

// NewMockURLStoreTree creates a new mock instance
func NewMockURLStoreTree(ctrl *gomock.Controller) *MockURLStoreTree {
	mock := &MockURLStoreTree{ctrl: ctrl}
	mock.recorder = &MockURLStoreTreeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockURLStoreTree) EXPECT() *MockURLStoreTreeMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockURLStoreTree) Add(id int, key string, data interface{}) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", id, key, data)
	ret0, _ := ret[0].(int)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockURLStoreTreeMockRecorder) Add(id, key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockURLStoreTree)(nil).Add), id, key, data)
}

// Get mocks base method
func (m *MockURLStoreTree) Get(path string, pvalues []string) (interface{}, []string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", path, pvalues)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].([]string)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockURLStoreTreeMockRecorder) Get(path, pvalues interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLStoreTree)(nil).Get), path, pvalues)
}

// Delete mocks base method
func (m *MockURLStoreTree) Delete(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockURLStoreTreeMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLStoreTree)(nil).Delete), id)
}

// String mocks base method
func (m *MockURLStoreTree) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String
func (mr *MockURLStoreTreeMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockURLStoreTree)(nil).String))
}

// Count mocks base method
func (m *MockURLStoreTree) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count
func (mr *MockURLStoreTreeMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockURLStoreTree)(nil).Count))
}
