// Code generated by MockGen. DO NOT EDIT.
// Source: app/urlstore/urlstore.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	urlstore "github.com/hotstone-seo/hotstone-server/app/urlstore"
	reflect "reflect"
)

// MockURLStore is a mock of URLStore interface
type MockURLStore struct {
	ctrl     *gomock.Controller
	recorder *MockURLStoreMockRecorder
}

// MockURLStoreMockRecorder is the mock recorder for MockURLStore
type MockURLStoreMockRecorder struct {
	mock *MockURLStore
}

// NewMockURLStore creates a new mock instance
func NewMockURLStore(ctrl *gomock.Controller) *MockURLStore {
	mock := &MockURLStore{ctrl: ctrl}
	mock.recorder = &MockURLStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockURLStore) EXPECT() *MockURLStoreMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockURLStore) Get(path string) (int, urlstore.VarMap) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", path)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(urlstore.VarMap)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockURLStoreMockRecorder) Get(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLStore)(nil).Get), path)
}

// Add mocks base method
func (m *MockURLStore) Add(id int, key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", id, key)
}

// Add indicates an expected call of Add
func (mr *MockURLStoreMockRecorder) Add(id, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockURLStore)(nil).Add), id, key)
}

// Update mocks base method
func (m *MockURLStore) Update(id int, key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", id, key)
}

// Update indicates an expected call of Update
func (mr *MockURLStoreMockRecorder) Update(id, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockURLStore)(nil).Update), id, key)
}

// Delete mocks base method
func (m *MockURLStore) Delete(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockURLStoreMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLStore)(nil).Delete), id)
}

// Count mocks base method
func (m *MockURLStore) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count
func (mr *MockURLStoreMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockURLStore)(nil).Count))
}
