@secure_token = secure_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAaG90c3RvbmUuY29tIiwiZXhwIjo0NzQyOTQxNzU3LCJwaWN0dXJlIjoiaHR0cHM6Ly9saDUuZ29vZ2xldXNlcmNvbnRlbnQuY29tLy1FNG5hTlVWMEo4by9BQUFBQUFBQUFBSS9BQUFBQUFBQUFBQS93Y3ZMcXR6RnlpWS9waG90by5qcGcifQ.dnaLjAtB2QZBc4RlBpY73Fd5vx3ZtPf1W49cVwxuEhQ

### Retrieve Client Keys

GET http://localhost:8089/api/client-keys
Cookie: {{secure_token}}

### Add New Client Key
POST http://localhost:8089/api/client-keys
Cookie: {{secure_token}}
content-type: application/json

{
    "name" :"Hotel Frontend JADI"
}
