// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/analyt (interfaces: ReportRepo)

// Package analyt_mock is a generated GoMock package.
package analyt_mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	analyt "github.com/hotstone-seo/hotstone-seo/analyt"
	repository "github.com/hotstone-seo/hotstone-seo/server/repository"
	url "net/url"
	reflect "reflect"
)

// MockReportRepo is a mock of ReportRepo interface
type MockReportRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepoMockRecorder
}

// MockReportRepoMockRecorder is the mock recorder for MockReportRepo
type MockReportRepoMockRecorder struct {
	mock *MockReportRepo
}

// NewMockReportRepo creates a new mock instance
func NewMockReportRepo(ctrl *gomock.Controller) *MockReportRepo {
	mock := &MockReportRepo{ctrl: ctrl}
	mock.recorder = &MockReportRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportRepo) EXPECT() *MockReportRepoMockRecorder {
	return m.recorder
}

// CountMatched mocks base method
func (m *MockReportRepo) CountMatched(arg0 context.Context, arg1 url.Values) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMatched", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMatched indicates an expected call of CountMatched
func (mr *MockReportRepoMockRecorder) CountMatched(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMatched", reflect.TypeOf((*MockReportRepo)(nil).CountMatched), arg0, arg1)
}

// CountUniquePage mocks base method
func (m *MockReportRepo) CountUniquePage(arg0 context.Context, arg1 url.Values) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUniquePage", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUniquePage indicates an expected call of CountUniquePage
func (mr *MockReportRepoMockRecorder) CountUniquePage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUniquePage", reflect.TypeOf((*MockReportRepo)(nil).CountUniquePage), arg0, arg1)
}

// DailyReports mocks base method
func (m *MockReportRepo) DailyReports(arg0 context.Context, arg1, arg2, arg3 string) ([]*analyt.DailyReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DailyReports", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*analyt.DailyReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DailyReports indicates an expected call of DailyReports
func (mr *MockReportRepoMockRecorder) DailyReports(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DailyReports", reflect.TypeOf((*MockReportRepo)(nil).DailyReports), arg0, arg1, arg2, arg3)
}

// MismatchReports mocks base method
func (m *MockReportRepo) MismatchReports(arg0 context.Context, arg1 repository.PaginationParam) ([]*analyt.MismatchReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MismatchReports", arg0, arg1)
	ret0, _ := ret[0].([]*analyt.MismatchReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MismatchReports indicates an expected call of MismatchReports
func (mr *MockReportRepoMockRecorder) MismatchReports(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MismatchReports", reflect.TypeOf((*MockReportRepo)(nil).MismatchReports), arg0, arg1)
}
