version: "3"
services:
  ht-analyt:
    image: timescale/timescaledb:latest-pg11
    environment:
      PGDATA: /data/postgres
      POSTGRES: postgres
      POSTGRES_PASSWORD: pgpass
    volumes:
    - ht-analyt:/data/postgres
    ports:
    - 5433:5432
    networks:
    - ht-analyt
    restart: unless-stopped
  ht-main:
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES: postgres
      POSTGRES_PASSWORD: pgpass
    volumes:
    - ht-main:/data/postgres
    ports:
    - 5432:5432
    networks:
    - ht-main
    restart: unless-stopped
  redis:
    image: redis:4.0.5-alpine
    command: redis-server --requirepass "redispass"
    volumes:
    - redis:/data
    ports:
    - 6379:6379
    networks:
    - redis
networks:
  ht-analyt:
    driver: bridge
  ht-main:
    driver: bridge
  redis: null
volumes:
  ht-analyt: null
  ht-main: null
  redis: null
