#!/bin/bash
set -e

CHECKSUM_DATA=$(cksum typical/descriptor.go)

if ! [ -s .typical-tmp/checksum ]; then
	mkdir -p .typical-tmp
	cksum typical/descriptor.go > .typical-tmp/checksum
else
	CHECKSUM_UPDATED=$([ "$CHECKSUM_DATA" == "$(cat .typical-tmp/checksum )" ] ; echo $?)
fi

if [ "$CHECKSUM_UPDATED" == "1" ] || ! [[ -f bin/hotstone-seo-buildtool ]] ; then 
	echo $CHECKSUM_DATA > .typical-tmp/checksum
	echo "Compile Typical-Build"
	go build -o bin/hotstone-seo-buildtool ./cmd/hotstone-seo-buildtool
fi

./bin/hotstone-seo-buildtool $@