#!/bin/bash
set -e

CHECKSUM_DATA=$(cksum typical/context.go)

if ! [ -s .typical-metadata/checksum ]; then
	mkdir -p .typical-metadata
	cksum typical/context.go > .typical-metadata/checksum
else
	CHECKSUM_UPDATED=$([ "$CHECKSUM_DATA" == "$(cat .typical-metadata/checksum )" ] ; echo $?)
fi

if [ "$CHECKSUM_UPDATED" == "1" ] || ! [[ -f bin/hotstone-server-prebuilder ]] ; then 
	echo $CHECKSUM_DATA > .typical-metadata/checksum
	echo "Build the prebuilder"
	go build -o bin/hotstone-server-prebuilder ./cmd/hotstone-server-prebuilder
fi

./bin/hotstone-server-prebuilder $CHECKSUM_UPDATED
./bin/hotstone-server-buildtool $@