// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/app/service (interfaces: AuthGoogleService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo"
	reflect "reflect"
)

// MockAuthGoogleService is a mock of AuthGoogleService interface
type MockAuthGoogleService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthGoogleServiceMockRecorder
}

// MockAuthGoogleServiceMockRecorder is the mock recorder for MockAuthGoogleService
type MockAuthGoogleServiceMockRecorder struct {
	mock *MockAuthGoogleService
}

// NewMockAuthGoogleService creates a new mock instance
func NewMockAuthGoogleService(ctrl *gomock.Controller) *MockAuthGoogleService {
	mock := &MockAuthGoogleService{ctrl: ctrl}
	mock.recorder = &MockAuthGoogleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthGoogleService) EXPECT() *MockAuthGoogleServiceMockRecorder {
	return m.recorder
}

// GetAuthCodeURL mocks base method
func (m *MockAuthGoogleService) GetAuthCodeURL(arg0 echo.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthCodeURL", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthCodeURL indicates an expected call of GetAuthCodeURL
func (mr *MockAuthGoogleServiceMockRecorder) GetAuthCodeURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthCodeURL", reflect.TypeOf((*MockAuthGoogleService)(nil).GetAuthCodeURL), arg0)
}

// GetThenDeleteJwtToken mocks base method
func (m *MockAuthGoogleService) GetThenDeleteJwtToken(arg0 context.Context, arg1 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThenDeleteJwtToken", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThenDeleteJwtToken indicates an expected call of GetThenDeleteJwtToken
func (mr *MockAuthGoogleServiceMockRecorder) GetThenDeleteJwtToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThenDeleteJwtToken", reflect.TypeOf((*MockAuthGoogleService)(nil).GetThenDeleteJwtToken), arg0, arg1)
}

// VerifyCallback mocks base method
func (m *MockAuthGoogleService) VerifyCallback(arg0 echo.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCallback", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCallback indicates an expected call of VerifyCallback
func (mr *MockAuthGoogleServiceMockRecorder) VerifyCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCallback", reflect.TypeOf((*MockAuthGoogleService)(nil).VerifyCallback), arg0)
}
