// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/internal/api/service (interfaces: AuthService)

// Package service_mock is a generated GoMock package.
package service_mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	service "github.com/hotstone-seo/hotstone-seo/internal/api/service"
	oauth2google "github.com/hotstone-seo/hotstone-seo/pkg/oauth2google"
	reflect "reflect"
)

// MockAuthService is a mock of AuthService interface
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// BuildJwtClaims mocks base method
func (m *MockAuthService) BuildJwtClaims(arg0 context.Context, arg1 oauth2google.GoogleUser) (service.JwtClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildJwtClaims", arg0, arg1)
	ret0, _ := ret[0].(service.JwtClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildJwtClaims indicates an expected call of BuildJwtClaims
func (mr *MockAuthServiceMockRecorder) BuildJwtClaims(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildJwtClaims", reflect.TypeOf((*MockAuthService)(nil).BuildJwtClaims), arg0, arg1)
}

// GenerateJwtToken mocks base method
func (m *MockAuthService) GenerateJwtToken(arg0 service.JwtClaims, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJwtToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJwtToken indicates an expected call of GenerateJwtToken
func (mr *MockAuthServiceMockRecorder) GenerateJwtToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJwtToken", reflect.TypeOf((*MockAuthService)(nil).GenerateJwtToken), arg0, arg1)
}
