package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/hotstone-seo/hotstone-server/app/metric"
	"github.com/hotstone-seo/hotstone-server/app/repository"
	"github.com/hotstone-seo/hotstone-server/app/service"
	"github.com/hotstone-seo/hotstone-server/app/urlstore"
	"github.com/hotstone-seo/hotstone-server/typical"
)

func init() {
	typical.Descriptor.Constructors.Append(metric.NewMetricServer)
	typical.Descriptor.Constructors.Append(repository.NewDataSourceRepo)
	typical.Descriptor.Constructors.Append(repository.NewLocaleRepo)
	typical.Descriptor.Constructors.Append(repository.NewMetricsUnmatchedRepo)
	typical.Descriptor.Constructors.Append(repository.NewRuleRepo)
	typical.Descriptor.Constructors.Append(repository.NewTagRepo)
	typical.Descriptor.Constructors.Append(service.NewCenterService)
	typical.Descriptor.Constructors.Append(service.NewDataSourceService)
	typical.Descriptor.Constructors.Append(service.NewLocaleService)
	typical.Descriptor.Constructors.Append(service.NewMetricsUnmatchedService)
	typical.Descriptor.Constructors.Append(service.NewProviderService)
	typical.Descriptor.Constructors.Append(service.NewRuleService)
	typical.Descriptor.Constructors.Append(service.NewTagService)
	typical.Descriptor.Constructors.Append(urlstore.NewURLStoreServer)
	typical.Descriptor.Constructors.Append(urlstore.NewURLStoreSyncRepo)
	typical.Descriptor.Constructors.Append(urlstore.NewURLStoreSyncService)
}
