package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/hotstone-seo/hotstone-seo/app/repository"
	"github.com/hotstone-seo/hotstone-seo/app/service"
	"github.com/hotstone-seo/hotstone-seo/app/urlstore"
	"github.com/typical-go/typical-go/pkg/typapp"
)

func init() {
	typapp.AppendConstructor(
		repository.NewDataSourceRepo,
		repository.NewMetricsRuleMatchingRepo,
		repository.NewRuleRepo,
		repository.NewTagRepo,
		service.NewOauth2Config,
		service.NewAuthGoogleService,
		service.NewCenterService,
		service.NewDataSourceService,
		service.NewMetricsRuleMatchingService,
		service.NewProviderService,
		service.NewRuleService,
		service.NewTagService,
		urlstore.NewURLStoreServer,
		urlstore.NewURLStoreSyncRepo,
		urlstore.NewURLStoreSyncService,
	)
}
