### Heath Check

http://localhost:8089/application/health


### Dump Rule Tree

http://localhost:8089/api/provider/rule-tree

### Match Rule

POST http://localhost:8089/api/provider/match-rule
content-type: application/json

{
    "path": "/events/bingbang"
}

### Retrieve Data

POST http://localhost:8089/api/provider/retrieve-data
Content-Type: application/json
If-Modified-Since: Thu, 09 Apr 2020 05:32:56 UTC

{
    "data_source_id": 1, 
    "path_param": {
        "eventName":"bigbang"
    }
}


### Tags

POST http://localhost:8089/api/provider/tags
content-type: application/json

{

}

