### Match Rule

POST http://localhost:8089/p/match
content-type: application/json

{
    "path": "/events/bingbang"
}

### Tags

http://localhost:8089/p/rule/1?locale=en_US
If-Modified-Since: Thu, 16 Apr 2020 06:00:50 UTC


