@secure_token = secure_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhaHJpLmhpZGF5YXRAdGlrZXQuY29tIiwiZXhwIjoxNTg3Mzc3MDAyLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDUuZ29vZ2xldXNlcmNvbnRlbnQuY29tLy1FNG5hTlVWMEo4by9BQUFBQUFBQUFBSS9BQUFBQUFBQUFBQS93Y3ZMcXR6RnlpWS9waG90by5qcGcifQ.NnY_ijqa9kmHMg40tUjnVw_t7G2O_RyT-EP4XyVISZ0

### Retrieve Mismatched Rule

http://localhost:8089/api/metrics/mismatched
Cookie: {{secure_token}}

### Retrieve Rules

GET http://localhost:8089/api/rules
Cookie: {{secure_token}}

### Add New Rule
POST http://localhost:8089/api/rules
Cookie: {{secure_token}}
content-type: application/json

{
    "id" : null,
    "name" :"Airport Rules",
    "url_pattern" : "/airports",
    "data_source_id" : 1
}

### Update Rule
PUT http://localhost:8089/api/rules
Cookie: {{secure_token}}
content-type: application/json

{
    "id" : 1,
    "name" :"Airport Rule",
    "url_pattern" : "/airport",
    "data_source_id" : 2
}


### Delete Rule

DELETE http://localhost:8089/api/rules/100
Cookie: {{secure_token}}

### Retrieve Data Source

http://localhost:8089/api/data_sources
Cookie: {{secure_token}}

### Retrieve Data Source By ID

GET http://localhost:8089/api/data_sources/4
Cookie: {{secure_token}}

### Add New Data Source
POST http://localhost:8089/api/data_sources
Cookie: {{secure_token}}
content-type: application/json

{
    "id" : null,
    "name" :"Airport Data Source",
    "url" : "www.source.co/airport"
}


### Edit Data Source
PUT http://localhost:8089/api/data_sources
Cookie: {{secure_token}}
content-type: application/json

{
    "id" : 1,
    "name" :"Airport Data Source",
    "url" : "www.source.co/airportds"
}


### Delete Data Source

DELETE http://localhost:8089/api/data_sources/1
Cookie: {{secure_token}}

### Retrieve Audit Trail

http://localhost:8089/api/audit-trail
Cookie: {{secure_token}}

### Retrieve Tag
http://localhost:8089/api/tags
Cookie: {{secure_token}}

### Retrieve Tag By Rule ID & Locale
http://localhost:8089/api/tags
Cookie: {{secure_token}}
content-type: application/json

{
    "params": {"en_US": 1 }
}

### Add Meta Tag
POST http://localhost:8089/api/center/metaTag
Cookie: {{secure_token}}
content-type: application/json

{
    "locale": "en_US",
    "name": "meta",
    "content": "test 2",
    "rule_id": 9
}

### Edit Meta Tag
PUT http://localhost:8089/api/center/metaTag
Cookie: {{secure_token}}
content-type: application/json

{
    "locale": "en_US",
    "name": "description",
    "content": "Event with Path Params Description page",
    "id": 4,
    "rule_id": 4
}

### Add Title Tag
POST http://localhost:8089/api/center/titleTag
Cookie: {{secure_token}}
content-type: application/json

{
    "locale": "id_ID",
    "title": "Event Keren",
    "rule_id": 4
}

### Edit Title tag

PUT http://localhost:8089/api/center/titleTag
Cookie: {{secure_token}}
content-type: application/json

{
    "locale": "en_US",
    "title": "Event with Path Params Title Tag",
    "id": 3,
    "rule_id": 4
}

### Add Script Tag
POST http://localhost:8089/api/center/scriptTag
Cookie: {{secure_token}}
content-type: application/json

{
    "locale": "en_US",
    "source": "source.com",
    "rule_id": 4
}

### Add Script Tag
PUT http://localhost:8089/api/center/scriptTag
Cookie: {{secure_token}}
content-type: application/json

{
    "locale": "en_US",
    "source": "source.com",
    "id": 12,
    "rule_id": 4
}

### Add Canonical Tag
POST http://localhost:8089/api/center/canonicalTag
Cookie: {{secure_token}}
content-type: application/json

{
    "locale": "en_US",
    "href": "www.sampledata.com/src1.js",
    "rule_id": 4
}

### Edit Canonical Tag

PUT http://localhost:8089/api/center/canonicalTag
Cookie: {{secure_token}}
content-type: application/json

{
    "locale": "en_US",
    "href": "www.sampledata.com/src1.js",
    "id": 14,
    "rule_id": 4
}

### Analytic Number of Hit (based on Rule ID)
http://localhost:8089/api/metrics/hit
Cookie: {{secure_token}}
content-type: application/json

{
    "params": {"rule_id": 1 }
}

### Analytic Number of Unique Page (based on Rule ID)
http://localhost:8089/api/metrics/unique-page
Cookie: {{secure_token}}
content-type: application/json

{
    "params": {"rule_id": 1 }
}

### Analytic Number of Hit Count (based on date of range)
GET http://localhost:8089/api/metrics/hit/range?start=2020-04-08&end=2020-04-15
Cookie: {{secure_token}}

### Analytic Number of Hit Count (based on date of range & Rule ID)
GET http://localhost:8089/api/metrics/hit/range?start=2020-04-08&end=2020-04-15&rule_id=1
Cookie: {{secure_token}}
 

### Retrieve Rule By ID
GET http://localhost:8089/api/rules/1
Cookie: {{secure_token}}