package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typdep"
	"github.com/hotstone-seo/hotstone-seo/server"
	"github.com/hotstone-seo/hotstone-seo/server/config"
	"github.com/hotstone-seo/hotstone-seo/server/controller"
	"github.com/hotstone-seo/hotstone-seo/server/mock_repository"
	"github.com/hotstone-seo/hotstone-seo/server/mock_service"
	"github.com/hotstone-seo/hotstone-seo/server/repository"
	"github.com/hotstone-seo/hotstone-seo/server/service"
	"github.com/hotstone-seo/hotstone-seo/server/urlstore"
	"github.com/hotstone-seo/hotstone-seo/pkg"
	"github.com/hotstone-seo/hotstone-seo/pkg/grafana"
	"github.com/hotstone-seo/hotstone-seo/pkg/gsociallogin"
	"github.com/hotstone-seo/hotstone-seo/pkg/prometheus"
	
)

func init() {
	typapp.AppendConstructor(
		typdep.NewConstructor(repository.NewDataSourceRepo),
		typdep.NewConstructor(repository.NewMetricsRuleMatchingRepo),
		typdep.NewConstructor(repository.NewRuleRepo),
		typdep.NewConstructor(repository.NewTagRepo),
		typdep.NewConstructor(repository.NewURLSyncRepo),
		typdep.NewConstructor(service.NewCenterService),
		typdep.NewConstructor(service.NewDataSourceService),
		typdep.NewConstructor(service.NewMetricsRuleMatchingService),
		typdep.NewConstructor(service.NewProviderService),
		typdep.NewConstructor(service.NewRuleService),
		typdep.NewConstructor(service.NewTagService),
		typdep.NewConstructor(service.NewURLService),
	)
}