package dependency

// Autogenerated by Typical-Go. DO NOT EDIT.

import "github.com/hotstone-seo/hotstone-server/app/repository"
import "github.com/hotstone-seo/hotstone-server/app/service"
import "github.com/hotstone-seo/hotstone-server/typical"

func init() {
	typical.Context.Constructors.Append(repository.NewRuleRepo)
	typical.Context.Constructors.Append(service.NewRuleService)
}
