package dependency

// Autogenerated by Typical-Go. DO NOT EDIT.

import "github.com/hotstone-seo/hotstone-server/typical"

func init() {
	typical.Context.MockTargets.Append("app/repository/rule_repo.go")
	typical.Context.MockTargets.Append("app/service/rule_service.go")
}
