// Autogenerated by Typical-Go. DO NOT EDIT.

package dependency

import "github.com/hotstone-seo/hotstone-server/typical"

func init() {
	typical.Context.TestTargets.Append("./app")
	typical.Context.TestTargets.Append("./app/config")
}
