// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/server/repository (interfaces: RoleTypeRepo)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	repository "github.com/hotstone-seo/hotstone-seo/server/repository"
	reflect "reflect"
)

// MockRoleTypeRepo is a mock of RoleTypeRepo interface
type MockRoleTypeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoleTypeRepoMockRecorder
}

// MockRoleTypeRepoMockRecorder is the mock recorder for MockRoleTypeRepo
type MockRoleTypeRepoMockRecorder struct {
	mock *MockRoleTypeRepo
}

// NewMockRoleTypeRepo creates a new mock instance
func NewMockRoleTypeRepo(ctrl *gomock.Controller) *MockRoleTypeRepo {
	mock := &MockRoleTypeRepo{ctrl: ctrl}
	mock.recorder = &MockRoleTypeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRoleTypeRepo) EXPECT() *MockRoleTypeRepoMockRecorder {
	return m.recorder
}

// Find mocks base method
func (m *MockRoleTypeRepo) Find(arg0 context.Context, arg1 repository.PaginationParam) ([]*repository.RoleType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].([]*repository.RoleType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockRoleTypeRepoMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRoleTypeRepo)(nil).Find), arg0, arg1)
}

// FindOne mocks base method
func (m *MockRoleTypeRepo) FindOne(arg0 context.Context, arg1 int64) (*repository.RoleType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*repository.RoleType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne
func (mr *MockRoleTypeRepoMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockRoleTypeRepo)(nil).FindOne), arg0, arg1)
}

// Insert mocks base method
func (m *MockRoleTypeRepo) Insert(arg0 context.Context, arg1 repository.RoleType) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockRoleTypeRepoMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRoleTypeRepo)(nil).Insert), arg0, arg1)
}
