// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/server/service (interfaces: CenterService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	service "github.com/hotstone-seo/hotstone-seo/server/service"
	reflect "reflect"
)

// MockCenterService is a mock of CenterService interface
type MockCenterService struct {
	ctrl     *gomock.Controller
	recorder *MockCenterServiceMockRecorder
}

// MockCenterServiceMockRecorder is the mock recorder for MockCenterService
type MockCenterServiceMockRecorder struct {
	mock *MockCenterService
}

// NewMockCenterService creates a new mock instance
func NewMockCenterService(ctrl *gomock.Controller) *MockCenterService {
	mock := &MockCenterService{ctrl: ctrl}
	mock.recorder = &MockCenterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCenterService) EXPECT() *MockCenterServiceMockRecorder {
	return m.recorder
}

// AddCanonicalTag mocks base method
func (m *MockCenterService) AddCanonicalTag(arg0 context.Context, arg1 service.AddCanonicalTagRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCanonicalTag", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCanonicalTag indicates an expected call of AddCanonicalTag
func (mr *MockCenterServiceMockRecorder) AddCanonicalTag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCanonicalTag", reflect.TypeOf((*MockCenterService)(nil).AddCanonicalTag), arg0, arg1)
}

// AddMetaTag mocks base method
func (m *MockCenterService) AddMetaTag(arg0 context.Context, arg1 service.AddMetaTagRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetaTag", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMetaTag indicates an expected call of AddMetaTag
func (mr *MockCenterServiceMockRecorder) AddMetaTag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetaTag", reflect.TypeOf((*MockCenterService)(nil).AddMetaTag), arg0, arg1)
}

// AddScriptTag mocks base method
func (m *MockCenterService) AddScriptTag(arg0 context.Context, arg1 service.AddScriptTagRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddScriptTag", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddScriptTag indicates an expected call of AddScriptTag
func (mr *MockCenterServiceMockRecorder) AddScriptTag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddScriptTag", reflect.TypeOf((*MockCenterService)(nil).AddScriptTag), arg0, arg1)
}

// AddTitleTag mocks base method
func (m *MockCenterService) AddTitleTag(arg0 context.Context, arg1 service.AddTitleTagRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTitleTag", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTitleTag indicates an expected call of AddTitleTag
func (mr *MockCenterServiceMockRecorder) AddTitleTag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTitleTag", reflect.TypeOf((*MockCenterService)(nil).AddTitleTag), arg0, arg1)
}
