// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/internal/api/repository (interfaces: ModuleRepo)

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	repository "github.com/hotstone-seo/hotstone-seo/internal/api/repository"
	reflect "reflect"
)

// MockModuleRepo is a mock of ModuleRepo interface
type MockModuleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockModuleRepoMockRecorder
}

// MockModuleRepoMockRecorder is the mock recorder for MockModuleRepo
type MockModuleRepoMockRecorder struct {
	mock *MockModuleRepo
}

// NewMockModuleRepo creates a new mock instance
func NewMockModuleRepo(ctrl *gomock.Controller) *MockModuleRepo {
	mock := &MockModuleRepo{ctrl: ctrl}
	mock.recorder = &MockModuleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockModuleRepo) EXPECT() *MockModuleRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method
func (m *MockModuleRepo) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockModuleRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockModuleRepo)(nil).Delete), arg0, arg1)
}

// Find mocks base method
func (m *MockModuleRepo) Find(arg0 context.Context, arg1 repository.PaginationParam) ([]*repository.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].([]*repository.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockModuleRepoMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockModuleRepo)(nil).Find), arg0, arg1)
}

// FindOne mocks base method
func (m *MockModuleRepo) FindOne(arg0 context.Context, arg1 int64) (*repository.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*repository.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne
func (mr *MockModuleRepoMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockModuleRepo)(nil).FindOne), arg0, arg1)
}

// FindOneByName mocks base method
func (m *MockModuleRepo) FindOneByName(arg0 context.Context, arg1 string) (*repository.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByName", arg0, arg1)
	ret0, _ := ret[0].(*repository.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByName indicates an expected call of FindOneByName
func (mr *MockModuleRepoMockRecorder) FindOneByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByName", reflect.TypeOf((*MockModuleRepo)(nil).FindOneByName), arg0, arg1)
}

// Insert mocks base method
func (m *MockModuleRepo) Insert(arg0 context.Context, arg1 repository.Module) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockModuleRepoMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockModuleRepo)(nil).Insert), arg0, arg1)
}

// Update mocks base method
func (m *MockModuleRepo) Update(arg0 context.Context, arg1 repository.Module) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockModuleRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockModuleRepo)(nil).Update), arg0, arg1)
}
