// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hotstone-seo/hotstone-seo/internal/api/repository (interfaces: UserRoleRepo)

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	repository "github.com/hotstone-seo/hotstone-seo/internal/api/repository"
	reflect "reflect"
)

// MockUserRoleRepo is a mock of UserRoleRepo interface
type MockUserRoleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoleRepoMockRecorder
}

// MockUserRoleRepoMockRecorder is the mock recorder for MockUserRoleRepo
type MockUserRoleRepoMockRecorder struct {
	mock *MockUserRoleRepo
}

// NewMockUserRoleRepo creates a new mock instance
func NewMockUserRoleRepo(ctrl *gomock.Controller) *MockUserRoleRepo {
	mock := &MockUserRoleRepo{ctrl: ctrl}
	mock.recorder = &MockUserRoleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserRoleRepo) EXPECT() *MockUserRoleRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method
func (m *MockUserRoleRepo) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockUserRoleRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRoleRepo)(nil).Delete), arg0, arg1)
}

// Find mocks base method
func (m *MockUserRoleRepo) Find(arg0 context.Context) ([]*repository.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].([]*repository.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockUserRoleRepoMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserRoleRepo)(nil).Find), arg0)
}

// FindOne mocks base method
func (m *MockUserRoleRepo) FindOne(arg0 context.Context, arg1 int64) (*repository.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*repository.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne
func (mr *MockUserRoleRepoMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockUserRoleRepo)(nil).FindOne), arg0, arg1)
}

// FindOneByName mocks base method
func (m *MockUserRoleRepo) FindOneByName(arg0 context.Context, arg1 string) (*repository.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByName", arg0, arg1)
	ret0, _ := ret[0].(*repository.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByName indicates an expected call of FindOneByName
func (mr *MockUserRoleRepoMockRecorder) FindOneByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByName", reflect.TypeOf((*MockUserRoleRepo)(nil).FindOneByName), arg0, arg1)
}

// Insert mocks base method
func (m *MockUserRoleRepo) Insert(arg0 context.Context, arg1 repository.UserRole) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockUserRoleRepoMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockUserRoleRepo)(nil).Insert), arg0, arg1)
}

// Update mocks base method
func (m *MockUserRoleRepo) Update(arg0 context.Context, arg1 repository.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockUserRoleRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRoleRepo)(nil).Update), arg0, arg1)
}
