CREATE TABLE users (
    id serial PRIMARY KEY,
    email VARCHAR (60) NOT NULL UNIQUE,
    user_role_id INTEGER DEFAULT '0',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)