CREATE TABLE user_roles (
    id          INTEGER AUTO_INCREMENT PRIMARY KEY,
    "name"      VARCHAR (35) NOT NULL UNIQUE,
    menus       JSON NOT NULL DEFAULT JSON_TYPE("[]"),
    paths       JSON NOT NULL DEFAULT JSON_TYPE("[]"),
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
