CREATE TABLE users (
    id             INTEGER AUTO_INCREMENT PRIMARY KEY,
    email          VARCHAR (60) NOT NULL UNIQUE,
    user_role_id   INTEGER DEFAULT 0,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
