name: HotStoneClient
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npm test
        working-directory: ${{env.working-directory}}