CREATE TABLE rules (
    id serial PRIMARY KEY,
    "name" VARCHAR (255) NOT NULL,
    url_pattern TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);