CREATE TABLE rules (
    id serial PRIMARY KEY,
    data_source_id INTEGER,
    "name" VARCHAR (255) NOT NULL,
    url_pattern TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);